CREATE TABLE public.chat_sessions (
 id uuid PRIMARY KEY, actor_id varchar(128) NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE TABLE public.chat_messages (
 id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 session_id uuid NOT NULL REFERENCES public.chat_sessions(id) ON DELETE CASCADE,
 role varchar(20) NOT NULL, content text NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX chat_messages_session_idx ON public.chat_messages(session_id,id);
CREATE TABLE public.sql_change_proposals (
 id uuid PRIMARY KEY, actor_id varchar(128) NOT NULL, agent_run_id varchar(128) NOT NULL,
 sql_text text NOT NULL, explanation text NOT NULL, reason text NOT NULL, preview jsonb NOT NULL,
 status varchar(20) NOT NULL DEFAULT 'pending', decision_reason text, decided_by varchar(128),
 created_at timestamptz NOT NULL DEFAULT now(), resolved_at timestamptz,
 owner_id integer NOT NULL REFERENCES deanery.app_user(user_id),
 session_id uuid NOT NULL REFERENCES public.chat_sessions(id),
 expires_at timestamptz NOT NULL DEFAULT now()+interval '1 day',
 decision_key text, decision_approve boolean
);
CREATE INDEX sql_proposals_run_idx ON public.sql_change_proposals(agent_run_id,status);
