DO $$ BEGIN
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='deanery_runtime') THEN CREATE ROLE deanery_runtime LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='deanery_jobs') THEN CREATE ROLE deanery_jobs LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE NOINHERIT; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='deanery_reader') THEN CREATE ROLE deanery_reader NOLOGIN NOSUPERUSER NOBYPASSRLS; END IF;
 IF NOT EXISTS(SELECT FROM pg_roles WHERE rolname='deanery_upstream') THEN CREATE ROLE deanery_upstream LOGIN NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE; END IF;
END $$;
GRANT deanery_reader TO deanery_runtime, deanery_jobs;
